import "./globals.css";
import { Geist, Inter } from "next/font/google";
import { ThemeProvider } from 'next-themes'
import Header from "../components/shared/header";
import Footer from "../components/shared/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${inter.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className=" max-w-[75rem] mx-auto">
            <Header />
            <main className="min-h-screen">
              {children}
            </main>
          </div>
          <Footer />
        </ThemeProvider>
      </body>

    </html>
  );
}
